apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: secret-mysql
  namespace: database
spec:
  encryptedData:
    password: AgB7fGLGoPOyhhZgo0bDpw7QAxJM5qURxgIcloaobLmqYThkbXqsghYMdMVAc8Axz+BjZ7//zC272QGaE8UHdObtnGGbS1+VIyI6U6TGueVSNwQn06yssDuFYxiEav78VEwVRTPajAVtYrSe8PavS3GHW+w3FMC+Tj6rw0vpkPUQPf1bsjZ+qjKHGmZqwjkqCikNePSFLRgvDsJAcX23f4mhFYcHHGc1dYMbP0Ya4GTQX1z8sMdU1nIlv3UhJm/dwIVP/WhYYshesim9UQFLlZK3ZSh3lwih/yU2rxB3xK4vrV48NAxMn87gyBQiaaa102jJ6fv9Y7mHGx3G1DruRzQ8EfmmKk/7Z6spJj7SIu7gjSQT9cTh6FHrPtBps3LLP2wn1MoIsI6BtkS9n9ODgsG7M/qUOPjMl9wWgZkDeVsQdk2FA6UvC/EB5qtxXXx8fIzCQAPdhsdUwDbVuY4w68gwejWxtjsTyjC5O9qLFNrMNCUShnloKPrwxbV4cflOg0WCuZQRhB07Q7DnnUn3ChlMgp4gTMxWyfb13yv+qQS/f3S9/pU88HEOfuWKcUFduekE39skn02TTO7WSAB5YWY3RXnu26SAWgEm3fSfkNYJP1g11tmJiSU3cvqYbO6NfovGb0DMjLQKFQF7kXsPQj7k8b9M1NyPVCyTnnYjEntps/otlB42XE8T5T070h50V5bVUw0096UcAlJHGX3qATODzf6Axy/7aXR4
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: secret-mysql
      namespace: database

