apiVersion: v1
kind: Secret
metadata:
    name: secret-mysql
    namespace: database
stringData:
    password: ENC[AES256_GCM,data:3AMSr5U129vIJiakA+hFVDdC0NjeBpT3Fw==,iv:ZK9zHb/g2D0GvqOpXCkXifLdFl+3twC0WETaNsVPxsg=,tag:5oLlM2JLKAKk5gkyGwEt2Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-05-25T14:49:49Z"
    mac: ENC[AES256_GCM,data:sRGIYI4ZzSEeGqrfVb6kC5cke9pCepxQjc/XcdJpEcsj2FmmsZ8Fd7EWDvMV0xmlkHJARXAHleU9ppdbwauT6zYoAIsQDSkBVY0pL1C5H53JtnsVGxi1caRwKWSSFiWE1wMc7Esi/kikuQA1+zWIjjikFWJCK3vCx2q6MRb+AaQ=,iv:ePanjN7CcOlhch54jrrXrAgvgtY7LfZFQew1gxhSnsY=,tag:8/veQs1qUvcRtQywDhVvqw==,type:str]
    pgp:
        - created_at: "2023-05-25T14:49:48Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA9eDUG1qK5HYAQv/ZBMxUhDYJzGzwfJJdvHwPJpuyhe5O+II9mnJuypx7l/a
            PDcJ5xQ7Jg6IhOwjWo/Ov9il5lIDSq8n/D2Fcgk+Alw7m2MfrPfd9HGYtFWx/AxE
            WXmdh82dpb6BEXYu5nq3HnYxioIpGtFlLN6QVvvsiwkbpAmPS/4LtW4GtSP722yw
            pOJZvKotBzqjqfFREIsBbDc/Scr+tEJn6gZVsKa84yiwFP+3MeUob6y7gIqz6N7Z
            sF/0H0IoIl5PSKEWHSnlNcxhaKwkQcdQEq7e8QG8fKJAtnX6I1wl29t5iH3D9hd3
            dl6nxSIKi+sf/+h8hvpA9gq+JMykFlvUMggdYirEuaVwgLTL15PNu/kmn/FL3qWJ
            kqGGyZlBll340q9LmwMt3PTbXEjZqsYJDC137CK4O/yPzcq9PKm5sJAHgnRackoK
            lNU33pFL24FZNxeh5dlTn9FHuj7D3uvF7MlggpOCQAundlHAYOpLWQBDpm6HKAPh
            noa2imPEXU9RbEtG4sc60l4BnGQ+nSZuQb3fYJL7YHHs9Sa8mENg1RBTi3hUsJhn
            Cu4l/MfaYCoW5WMt+TluWnJ/TL8YBY+Em3uSQZuENx2S/JGAJ8AaF29s6x+yuKMr
            3B2aRYigIr10NA1Jv3TQ
            =wPz5
            -----END PGP MESSAGE-----
          fp: AE53031C6ABEA759
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
